### ISSUE TITLE
Lib apparently not compiling properly on AndroidStudio 3.0 Canary 7

### ISSUE THREAD

**Issue by JGeraldoLima** [Ilhasoft/data-binding-validator#10]
Hi again,

I just migrated to AS 3.0 beta to have more support with Room lib, but now your lib is not working anymore :/

Maybe it is a AS bug, not yours, but could you check this?

I didn't changed any validator property, just migrated to the last AS beta version (and obligatorily, gradle version to 4.1 and Android Plugin to 3.0.0-alpha7). It's printing the following:

```****/ data binding error ****msg:Cannot find the setter for attribute 'app:validateEmpty' with parameter type boolean on android.support.design.widget.TextInputEditText.```.

Here is my xml:

```xml
 <android.support.design.widget.TextInputLayout
            android:id="@+id/tiXpto"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginEnd="8dp"
            android:layout_marginRight="8dp"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <android.support.design.widget.TextInputEditText
                android:id="@+id/edXpto"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:hint="@string/add_xpto_name"
                android:inputType="textPersonName"
                android:text="@={xpto.name}"
                android:textSize="16sp"
                app:validateEmpty="@{true}"
                app:validateEmptyAutoDismiss="@{true}"
                app:validateEmptyMessage="@{@string/field_is_required}"/>
        </android.support.design.widget.TextInputLayout>

Any help will be apreciatted.

**Comment by oliveiradev** [comment]
Hi @JGeraldoLima , can you use in other canary versions?

**Comment by mikstur** [comment]
I am having the same issue on 3.0.0-alpha8. Any ideas?

**Comment by hshahdoost** [comment]
I am using 3.0.0-alpha9, and get the similar issue

**Comment by hshahdoost** [comment]
Apparently It's a problem Gradle 3.0 has with older sources, for now you can copy the binding classes (`DataBindings`, ...) to your own project and it works.

**Comment by BillionaireZ** [comment]
Still doesn't work on Android Studio 3.0 Beta 3

**Comment by pedrohfp** [comment]
Still doesnt't work on Android Studio 3.0 Beta 6, could not resolve the issue

**Comment by danielsanfr** [comment]
Please use this solution until a stable version of Android Studio arrives:

`implementation "com.github.Ilhasoft:data-binding-validator:master-SNAPSHOT"`

As soon as a stable version arrives we will release a new version.

**Comment by hshahdoost** [comment]
@danielsanfr I tried your solution, But it didn't change anything. The error is still there

**Comment by mrmar096** [comment]
Hi, today I was updating my version of  Android Studio to 3.0 and gradle to 4.1 and the ide report me this issue in compiling, seems these are stable versions. Can you solve this issue  for this stable versions?

**Comment by danielsanfr** [comment]
Sorry for the delay guys :pensive:. Version 1.0.0 has now been released.
