### ISSUE TITLE
It doesn't work with 'android.databinding.enableV2=true'

### ISSUE THREAD

**Issue by ghostman2013** [Ilhasoft/data-binding-validator#23]
> error: cannot find symbol
>     addMapper(new br.com.ilhasoft.support.validation.DataBinderMapperImpl());
>                                                     ^
>   symbol:   class DataBinderMapperImpl
>   location: package br.com.ilhasoft.support.validation
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 error
> 1 warning
> :app:compileDebugJavaWithJavac FAILED

Without the library all works.

**Comment by tianxu0836** [comment]
It doesn't work for me!!

**Comment by tianxu0836** [comment]
This thing is broken

**Comment by ghostman2013** [comment]
This bug was resolved by #27 pull request.
