### ISSUE TITLE
Failed to resolve: com.github.Ilhasoft:data-binding-validator:1.0.0

### ISSUE THREAD

**Issue by mnleano** [Ilhasoft/data-binding-validator#24]
Hey there, I found that a same issue has been raised before and he only forgot to add the maven repository link.

I have them both

        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.fabric.io/public' }

Well the problem is I have 2 maven repository. 
May I know where do you think the problem is here's my implementation

repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.fabric.io/public' }
    }
and

    implementation 'com.github.Ilhasoft:data-binding-validator:1.0.0'

Cheers!

**Comment by MikeDaniel18** [comment]
The build is failing hence why it can't be used: https://jitpack.io/#Ilhasoft/data-binding-validator

**Comment by rital-naik-adrosonic** [comment]
ERROR: Failed to resolve: com.github.Ilhasoft:data-binding-validator:1.0.0
I am getting  above error. However earlier my project was running fine. 

Any help would be appreciated. Its urgent

**Comment by ntn-santos** [comment]
Any updates regarding this bug? It is still possible to use this lib without updating to android x?

**Comment by rital-naik-adrosonic** [comment]
I think it is because of either upgrading android studio or gradle version. Am still in search of solution.

However Can I use this library by migrating my project to androidX?

**Comment by ntn-santos** [comment]
@rital-naik-adrosonic In order not to stop the project it was necessary to update the project to use android x and update lib to version 2.0.0

**Comment by rital-naik-adrosonic** [comment]
@ntn-santos  

In Project.gradle

**gradle version is** 
classpath "com.android.tools.build:gradle:3.4.0"

Dependency for Ilhasoft is added like following
def data_binding_validator = [:]
data_binding_validator.core = "com.github.Ilhasoft:data-binding-validator:$versions.arch"
deps.data_binding_validator = data_binding_validator

where version is 1.0.0(also the use of master-SNAPSHOT in place of version did not help)

**my compilesdkversion and targetsdkversion is 26**
**in gradle-wrapper.properties**
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

**Comment by koallann** [comment]
The version 1.0.0 was rebuilt.

https://jitpack.io/com/github/Ilhasoft/data-binding-validator/1.0.0/build.log

**Comment by rital-naik-adrosonic** [comment]
Thank a ton @allancslima  I am able to build my project. :)
