### ISSUE TITLE
1.0.0 is failing on JitPack

### ISSUE THREAD

**Issue by MikeDaniel18** [Ilhasoft/data-binding-validator#31]
As per here: 
https://jitpack.io/#Ilhasoft/data-binding-validator

logs:
https://jitpack.io/com/github/Ilhasoft/data-binding-validator/1.0.0/build.log

**Comment by koallann** [comment]
The version 1.0.0 was rebuilt.

https://jitpack.io/com/github/Ilhasoft/data-binding-validator/1.0.0/build.log
