### ISSUE TITLE
Empty validation error message

### ISSUE THREAD

**Issue by JGeraldoLima** [Ilhasoft/data-binding-validator#8]
Hi guys, nice to find other Maceioenses round here :)

So, I need to define an error message for empty validation (by the way, the empty may be used as a required validation? Maybe you can rename it or something like that), so how I'm suppose to get it?

I tried to add ```app:validateEmptyMessage="@string/<some_string>"```, similarly to the date validation, but this not exists :/

Can you help me oh this?

**Comment by johncordeiro** [comment]
Hey @JGeraldoLima, as you are using databinding you should do:
`app:validateEmptyMessage="@{@string/<some_string>}"`

**Comment by JGeraldoLima** [comment]
Hey @johncordeiro , thanks for the callback :)

So, I'm not sure that the the error showed to me was about this sintax (```@{}```), but later I'll try and then I'll come back here to confirm this. Meanwhile, I'm using regex to validate required fields...

**Comment by JGeraldoLima** [comment]
Hi @johncordeiro , it worked! My bad, I made other validations work with the same logic but I kept missing the empty ones Lol

Just lack of attention, sorry about that :/

Great lib man, thank you ;)
